//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodnoteWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class earthRegion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal earthRegion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoodnoteWPF.Properties.earthRegion", typeof(earthRegion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antarctica.
        /// </summary>
        internal static string Antarctica {
            get {
                return ResourceManager.GetString("Antarctica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia and New Zealand.
        /// </summary>
        internal static string AustraliaNewZealand {
            get {
                return ResourceManager.GetString("AustraliaNewZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caribbean.
        /// </summary>
        internal static string Caribbean {
            get {
                return ResourceManager.GetString("Caribbean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central America.
        /// </summary>
        internal static string CentralAmerica {
            get {
                return ResourceManager.GetString("CentralAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Asia.
        /// </summary>
        internal static string CentralAsia {
            get {
                return ResourceManager.GetString("CentralAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Africa.
        /// </summary>
        internal static string EasternAfrica {
            get {
                return ResourceManager.GetString("EasternAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Asia.
        /// </summary>
        internal static string EasternAsia {
            get {
                return ResourceManager.GetString("EasternAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Europe.
        /// </summary>
        internal static string EasternEurope {
            get {
                return ResourceManager.GetString("EasternEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melanesia, Micronesia, Polynesia.
        /// </summary>
        internal static string MelanesiaMicronesiaPolynesia {
            get {
                return ResourceManager.GetString("MelanesiaMicronesiaPolynesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Africa.
        /// </summary>
        internal static string MiddleAfrica {
            get {
                return ResourceManager.GetString("MiddleAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North America.
        /// </summary>
        internal static string NorthAmerica {
            get {
                return ResourceManager.GetString("NorthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Africa.
        /// </summary>
        internal static string NorthernAfrica {
            get {
                return ResourceManager.GetString("NorthernAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Europe.
        /// </summary>
        internal static string NorthernEurope {
            get {
                return ResourceManager.GetString("NorthernEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South America.
        /// </summary>
        internal static string SouthAmerica {
            get {
                return ResourceManager.GetString("SouthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southeastern Asia.
        /// </summary>
        internal static string SoutheasternAsia {
            get {
                return ResourceManager.GetString("SoutheasternAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Africa.
        /// </summary>
        internal static string SouthernAfrica {
            get {
                return ResourceManager.GetString("SouthernAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Asia.
        /// </summary>
        internal static string SouthernAsia {
            get {
                return ResourceManager.GetString("SouthernAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Europe.
        /// </summary>
        internal static string SouthernEurope {
            get {
                return ResourceManager.GetString("SouthernEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Africa.
        /// </summary>
        internal static string WesternAfrica {
            get {
                return ResourceManager.GetString("WesternAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Asia.
        /// </summary>
        internal static string WesternAsia {
            get {
                return ResourceManager.GetString("WesternAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Europe.
        /// </summary>
        internal static string WesternEurope {
            get {
                return ResourceManager.GetString("WesternEurope", resourceCulture);
            }
        }
    }
}
