//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodnoteMobileUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class biologyClass {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal biologyClass() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoodnoteMobileUI.Properties.biologyClass", typeof(biologyClass).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clade.
        /// </summary>
        internal static string Clade {
            get {
                return ResourceManager.GetString("Clade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neognathae.
        /// </summary>
        internal static string Clade_Neognathae {
            get {
                return ResourceManager.GetString("Clade_Neognathae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palaeognathae.
        /// </summary>
        internal static string Clade_Palaeognathae {
            get {
                return ResourceManager.GetString("Clade_Palaeognathae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aepyornithiformes.
        /// </summary>
        internal static string Order_Aepyornithiformes {
            get {
                return ResourceManager.GetString("Order_Aepyornithiformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apterygiformes.
        /// </summary>
        internal static string Order_Apterygiformes {
            get {
                return ResourceManager.GetString("Order_Apterygiformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casuariiformes.
        /// </summary>
        internal static string Order_Casuariiformes {
            get {
                return ResourceManager.GetString("Order_Casuariiformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinornithiformes.
        /// </summary>
        internal static string Order_Dinornithiformes {
            get {
                return ResourceManager.GetString("Order_Dinornithiformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithornithiformes.
        /// </summary>
        internal static string Order_Lithornithiformes {
            get {
                return ResourceManager.GetString("Order_Lithornithiformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rheiformes.
        /// </summary>
        internal static string Order_Rheiformes {
            get {
                return ResourceManager.GetString("Order_Rheiformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struthioniformes.
        /// </summary>
        internal static string Order_Struthioniformes {
            get {
                return ResourceManager.GetString("Order_Struthioniformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinamiformes.
        /// </summary>
        internal static string Order_Tinamiformes {
            get {
                return ResourceManager.GetString("Order_Tinamiformes", resourceCulture);
            }
        }
    }
}
